# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stt.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tstt.proto\x12\x03stt\"\x07\n\x05\x45mpty\"H\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x14\n\x0cmodel_status\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\"w\n\nAudioChunk\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x16\n\x0eparticipant_id\x18\x03 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x04 \x01(\x03\x12\x13\n\x0bsample_rate\x18\x05 \x01(\x05\"\xa2\x01\n\x0fTranscriptEvent\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08is_final\x18\x02 \x01(\x08\x12\x15\n\rtranscript_id\x18\x03 \x01(\t\x12\x16\n\x0eparticipant_id\x18\x04 \x01(\t\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x14\n\x0ctimestamp_ms\x18\x06 \x01(\x03\x12\x16\n\x0espeech_started\x18\x07 \x01(\x08\x32}\n\x0cSpeechToText\x12=\n\x10StreamTranscribe\x12\x0f.stt.AudioChunk\x1a\x14.stt.TranscriptEvent(\x01\x30\x01\x12.\n\x0bHealthCheck\x12\n.stt.Empty\x1a\x13.stt.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=18
  _globals['_EMPTY']._serialized_end=25
  _globals['_HEALTHRESPONSE']._serialized_start=27
  _globals['_HEALTHRESPONSE']._serialized_end=99
  _globals['_AUDIOCHUNK']._serialized_start=101
  _globals['_AUDIOCHUNK']._serialized_end=220
  _globals['_TRANSCRIPTEVENT']._serialized_start=223
  _globals['_TRANSCRIPTEVENT']._serialized_end=385
  _globals['_SPEECHTOTEXT']._serialized_start=387
  _globals['_SPEECHTOTEXT']._serialized_end=512
# @@protoc_insertion_point(module_scope)
