# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stt.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tstt.proto\x12\x03stt\"\x07\n\x05\x45mpty\"H\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x14\n\x0cmodel_status\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\"8\n\rWarmupRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x02 \x01(\x05\"\\\n\x0eWarmupResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0ewarmup_time_ms\x18\x02 \x01(\x05\x12\x10\n\x08provider\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"\x89\x01\n\nAudioChunk\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x16\n\x0eparticipant_id\x18\x03 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x04 \x01(\x03\x12\x13\n\x0bsample_rate\x18\x05 \x01(\x05\x12\x10\n\x08language\x18\x06 \x01(\t\"\xda\x01\n\x0fTranscriptEvent\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08is_final\x18\x02 \x01(\x08\x12\x15\n\rtranscript_id\x18\x03 \x01(\t\x12\x16\n\x0eparticipant_id\x18\x04 \x01(\t\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x14\n\x0ctimestamp_ms\x18\x06 \x01(\x03\x12\x16\n\x0espeech_started\x18\x07 \x01(\x08\x12\x19\n\x11\x64\x65tected_language\x18\x08 \x01(\t\x12\x1b\n\x13language_confidence\x18\t \x01(\x02\x32\xb0\x01\n\x0cSpeechToText\x12=\n\x10StreamTranscribe\x12\x0f.stt.AudioChunk\x1a\x14.stt.TranscriptEvent(\x01\x30\x01\x12.\n\x0bHealthCheck\x12\n.stt.Empty\x1a\x13.stt.HealthResponse\x12\x31\n\x06Warmup\x12\x12.stt.WarmupRequest\x1a\x13.stt.WarmupResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=18
  _globals['_EMPTY']._serialized_end=25
  _globals['_HEALTHRESPONSE']._serialized_start=27
  _globals['_HEALTHRESPONSE']._serialized_end=99
  _globals['_WARMUPREQUEST']._serialized_start=101
  _globals['_WARMUPREQUEST']._serialized_end=157
  _globals['_WARMUPRESPONSE']._serialized_start=159
  _globals['_WARMUPRESPONSE']._serialized_end=251
  _globals['_AUDIOCHUNK']._serialized_start=254
  _globals['_AUDIOCHUNK']._serialized_end=391
  _globals['_TRANSCRIPTEVENT']._serialized_start=394
  _globals['_TRANSCRIPTEVENT']._serialized_end=612
  _globals['_SPEECHTOTEXT']._serialized_start=615
  _globals['_SPEECHTOTEXT']._serialized_end=791
# @@protoc_insertion_point(module_scope)
