# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """AgentService - Service exposed by session-management server
    Agents connect TO this service using the SDK
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAgent = channel.unary_unary(
                '/stella.agent.v1.AgentService/RegisterAgent',
                request_serializer=agent__pb2.RegisterAgentRequest.SerializeToString,
                response_deserializer=agent__pb2.RegisterAgentResponse.FromString,
                _registered_method=True)
        self.AgentStream = channel.stream_stream(
                '/stella.agent.v1.AgentService/AgentStream',
                request_serializer=agent__pb2.AgentOutputProto.SerializeToString,
                response_deserializer=agent__pb2.AgentInputProto.FromString,
                _registered_method=True)
        self.SendInterrupt = channel.unary_unary(
                '/stella.agent.v1.AgentService/SendInterrupt',
                request_serializer=agent__pb2.InterruptRequest.SerializeToString,
                response_deserializer=agent__pb2.InterruptResponse.FromString,
                _registered_method=True)
        self.EndSession = channel.unary_unary(
                '/stella.agent.v1.AgentService/EndSession',
                request_serializer=agent__pb2.EndSessionRequest.SerializeToString,
                response_deserializer=agent__pb2.EndSessionResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/stella.agent.v1.AgentService/HealthCheck',
                request_serializer=agent__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=agent__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """AgentService - Service exposed by session-management server
    Agents connect TO this service using the SDK
    """

    def RegisterAgent(self, request, context):
        """Register an agent with a session
        Agent calls this to join a session and receive configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AgentStream(self, request_iterator, context):
        """Bidirectional stream for agent communication
        Agent receives inputs, sends outputs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendInterrupt(self, request, context):
        """Send interrupt signal to agent (fast path for barge-in)
        Server calls this when user starts speaking
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndSession(self, request, context):
        """Agent signals session end
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=agent__pb2.RegisterAgentRequest.FromString,
                    response_serializer=agent__pb2.RegisterAgentResponse.SerializeToString,
            ),
            'AgentStream': grpc.stream_stream_rpc_method_handler(
                    servicer.AgentStream,
                    request_deserializer=agent__pb2.AgentOutputProto.FromString,
                    response_serializer=agent__pb2.AgentInputProto.SerializeToString,
            ),
            'SendInterrupt': grpc.unary_unary_rpc_method_handler(
                    servicer.SendInterrupt,
                    request_deserializer=agent__pb2.InterruptRequest.FromString,
                    response_serializer=agent__pb2.InterruptResponse.SerializeToString,
            ),
            'EndSession': grpc.unary_unary_rpc_method_handler(
                    servicer.EndSession,
                    request_deserializer=agent__pb2.EndSessionRequest.FromString,
                    response_serializer=agent__pb2.EndSessionResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=agent__pb2.HealthCheckRequest.FromString,
                    response_serializer=agent__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stella.agent.v1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stella.agent.v1.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """AgentService - Service exposed by session-management server
    Agents connect TO this service using the SDK
    """

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stella.agent.v1.AgentService/RegisterAgent',
            agent__pb2.RegisterAgentRequest.SerializeToString,
            agent__pb2.RegisterAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AgentStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/stella.agent.v1.AgentService/AgentStream',
            agent__pb2.AgentOutputProto.SerializeToString,
            agent__pb2.AgentInputProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendInterrupt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stella.agent.v1.AgentService/SendInterrupt',
            agent__pb2.InterruptRequest.SerializeToString,
            agent__pb2.InterruptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stella.agent.v1.AgentService/EndSession',
            agent__pb2.EndSessionRequest.SerializeToString,
            agent__pb2.EndSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stella.agent.v1.AgentService/HealthCheck',
            agent__pb2.HealthCheckRequest.SerializeToString,
            agent__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
