# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from stella_agent_sdk._grpc import state_machine_pb2 as state__machine__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in state_machine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StateMachineServiceStub(object):
    """StateMachineService - Service for managing conversation state machine
    Agents call this service to track conversation progress
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Initialize = channel.unary_unary(
                '/stella.statemachine.v1.StateMachineService/Initialize',
                request_serializer=state__machine__pb2.InitializeRequest.SerializeToString,
                response_deserializer=state__machine__pb2.InitializeResponse.FromString,
                _registered_method=True)
        self.CompleteTask = channel.unary_unary(
                '/stella.statemachine.v1.StateMachineService/CompleteTask',
                request_serializer=state__machine__pb2.CompleteTaskRequest.SerializeToString,
                response_deserializer=state__machine__pb2.CompleteTaskResponse.FromString,
                _registered_method=True)
        self.SetDeliverable = channel.unary_unary(
                '/stella.statemachine.v1.StateMachineService/SetDeliverable',
                request_serializer=state__machine__pb2.SetDeliverableRequest.SerializeToString,
                response_deserializer=state__machine__pb2.SetDeliverableResponse.FromString,
                _registered_method=True)
        self.GetCurrentState = channel.unary_unary(
                '/stella.statemachine.v1.StateMachineService/GetCurrentState',
                request_serializer=state__machine__pb2.GetCurrentStateRequest.SerializeToString,
                response_deserializer=state__machine__pb2.GetCurrentStateResponse.FromString,
                _registered_method=True)
        self.GetPendingTasks = channel.unary_unary(
                '/stella.statemachine.v1.StateMachineService/GetPendingTasks',
                request_serializer=state__machine__pb2.GetPendingTasksRequest.SerializeToString,
                response_deserializer=state__machine__pb2.GetPendingTasksResponse.FromString,
                _registered_method=True)
        self.GetPendingDeliverables = channel.unary_unary(
                '/stella.statemachine.v1.StateMachineService/GetPendingDeliverables',
                request_serializer=state__machine__pb2.GetPendingDeliverablesRequest.SerializeToString,
                response_deserializer=state__machine__pb2.GetPendingDeliverablesResponse.FromString,
                _registered_method=True)
        self.IncrementTurn = channel.unary_unary(
                '/stella.statemachine.v1.StateMachineService/IncrementTurn',
                request_serializer=state__machine__pb2.IncrementTurnRequest.SerializeToString,
                response_deserializer=state__machine__pb2.IncrementTurnResponse.FromString,
                _registered_method=True)
        self.GetCollectedDeliverables = channel.unary_unary(
                '/stella.statemachine.v1.StateMachineService/GetCollectedDeliverables',
                request_serializer=state__machine__pb2.GetCollectedDeliverablesRequest.SerializeToString,
                response_deserializer=state__machine__pb2.GetCollectedDeliverablesResponse.FromString,
                _registered_method=True)
        self.GetFullState = channel.unary_unary(
                '/stella.statemachine.v1.StateMachineService/GetFullState',
                request_serializer=state__machine__pb2.GetFullStateRequest.SerializeToString,
                response_deserializer=state__machine__pb2.GetFullStateResponse.FromString,
                _registered_method=True)


class StateMachineServiceServicer(object):
    """StateMachineService - Service for managing conversation state machine
    Agents call this service to track conversation progress
    """

    def Initialize(self, request, context):
        """Initialize state machine for a session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteTask(self, request, context):
        """Complete a task by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDeliverable(self, request, context):
        """Set a deliverable value
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentState(self, request, context):
        """Get current state info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingTasks(self, request, context):
        """Get pending tasks in current state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingDeliverables(self, request, context):
        """Get pending deliverables in current state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IncrementTurn(self, request, context):
        """Increment turn counter (no progress made)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollectedDeliverables(self, request, context):
        """Get all collected deliverables
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFullState(self, request, context):
        """Get full state machine state (for frontend updates)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StateMachineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialize,
                    request_deserializer=state__machine__pb2.InitializeRequest.FromString,
                    response_serializer=state__machine__pb2.InitializeResponse.SerializeToString,
            ),
            'CompleteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteTask,
                    request_deserializer=state__machine__pb2.CompleteTaskRequest.FromString,
                    response_serializer=state__machine__pb2.CompleteTaskResponse.SerializeToString,
            ),
            'SetDeliverable': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDeliverable,
                    request_deserializer=state__machine__pb2.SetDeliverableRequest.FromString,
                    response_serializer=state__machine__pb2.SetDeliverableResponse.SerializeToString,
            ),
            'GetCurrentState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentState,
                    request_deserializer=state__machine__pb2.GetCurrentStateRequest.FromString,
                    response_serializer=state__machine__pb2.GetCurrentStateResponse.SerializeToString,
            ),
            'GetPendingTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingTasks,
                    request_deserializer=state__machine__pb2.GetPendingTasksRequest.FromString,
                    response_serializer=state__machine__pb2.GetPendingTasksResponse.SerializeToString,
            ),
            'GetPendingDeliverables': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingDeliverables,
                    request_deserializer=state__machine__pb2.GetPendingDeliverablesRequest.FromString,
                    response_serializer=state__machine__pb2.GetPendingDeliverablesResponse.SerializeToString,
            ),
            'IncrementTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.IncrementTurn,
                    request_deserializer=state__machine__pb2.IncrementTurnRequest.FromString,
                    response_serializer=state__machine__pb2.IncrementTurnResponse.SerializeToString,
            ),
            'GetCollectedDeliverables': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollectedDeliverables,
                    request_deserializer=state__machine__pb2.GetCollectedDeliverablesRequest.FromString,
                    response_serializer=state__machine__pb2.GetCollectedDeliverablesResponse.SerializeToString,
            ),
            'GetFullState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFullState,
                    request_deserializer=state__machine__pb2.GetFullStateRequest.FromString,
                    response_serializer=state__machine__pb2.GetFullStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stella.statemachine.v1.StateMachineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stella.statemachine.v1.StateMachineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StateMachineService(object):
    """StateMachineService - Service for managing conversation state machine
    Agents call this service to track conversation progress
    """

    @staticmethod
    def Initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stella.statemachine.v1.StateMachineService/Initialize',
            state__machine__pb2.InitializeRequest.SerializeToString,
            state__machine__pb2.InitializeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stella.statemachine.v1.StateMachineService/CompleteTask',
            state__machine__pb2.CompleteTaskRequest.SerializeToString,
            state__machine__pb2.CompleteTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDeliverable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stella.statemachine.v1.StateMachineService/SetDeliverable',
            state__machine__pb2.SetDeliverableRequest.SerializeToString,
            state__machine__pb2.SetDeliverableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stella.statemachine.v1.StateMachineService/GetCurrentState',
            state__machine__pb2.GetCurrentStateRequest.SerializeToString,
            state__machine__pb2.GetCurrentStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stella.statemachine.v1.StateMachineService/GetPendingTasks',
            state__machine__pb2.GetPendingTasksRequest.SerializeToString,
            state__machine__pb2.GetPendingTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingDeliverables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stella.statemachine.v1.StateMachineService/GetPendingDeliverables',
            state__machine__pb2.GetPendingDeliverablesRequest.SerializeToString,
            state__machine__pb2.GetPendingDeliverablesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IncrementTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stella.statemachine.v1.StateMachineService/IncrementTurn',
            state__machine__pb2.IncrementTurnRequest.SerializeToString,
            state__machine__pb2.IncrementTurnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollectedDeliverables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stella.statemachine.v1.StateMachineService/GetCollectedDeliverables',
            state__machine__pb2.GetCollectedDeliverablesRequest.SerializeToString,
            state__machine__pb2.GetCollectedDeliverablesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFullState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stella.statemachine.v1.StateMachineService/GetFullState',
            state__machine__pb2.GetFullStateRequest.SerializeToString,
            state__machine__pb2.GetFullStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
